[package]
name = "pita"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.27", features= ["derive"] }
nom = "8.0.0"
nom-language = "0.1.0"
rc-slice2 = "0.4.1"
rpds = "1.1.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[profile.release]
debug = 1
